package constants

const DEFAULT_REGISTRATION_SERVICE_INTERVAL_IN_MINUTES = 60
const REGISTRATION_SERVICE_INTERVAL_IN_MINUTES_ENV = "CC_IPR_REGISTRATION_INTERVAL_MINUTES"
const LOG_LEVEL_FLAG = "log-level"
const LOG_LEVEL_ENV = "LOG_LEVEL"
